### ISSUE TITLE
problem with contract.deployed() method in deploy.js

### ISSUE THREAD

**Issue by Vimal-Dubey** [kshitijofficial/chaiDapp#2]
contract is compiling successfully  but script is reflecting some error while running.
error is specified below - 

    PS E:\projectmain\CoffeePilao> npx hardhat run scripts/deploy.js
    TypeError: contract.deployed is not a function
    at main (E:\projectmain\CoffeePilao\scripts\deploy.js:30:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by khadar1020** [comment]
[Vimal-Dubey](https://github.com/Vimal-Dubey) did you find the solution

**Comment by Vimal-Dubey** [comment]
yes, It was a version issue

**Comment by khadar1020** [comment]
can you tell me where we have to change the code [Vimal-Dubey](https://github.com/Vimal-Dubey)

**Comment by Vimal-Dubey** [comment]
you  need to change the way you are importing ethers
